auth:
  ## @param auth.enabled Enable authentication
  ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
  ##
  enabled: true
  ## @param auth.rootUser MongoDB(&reg;) root user
  ##
  rootUser: root
  ## @param auth.rootPassword MongoDB(&reg;) root password
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#setting-the-root-user-and-password-on-first-run
  ##
  rootPassword: ""
  ## MongoDB(&reg;) custom users and databases
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#creating-a-user-and-database-on-first-run
  ## @param auth.usernames List of custom users to be created during the initialization
  ## @param auth.passwords List of passwords for the custom users set at `auth.usernames`
  ## @param auth.databases List of custom databases to be created during the initialization
  ##
  usernames: [""]
  passwords: [""]
  databases: [""]
persistence:
  enabled: true
  size: 10Gi
replicaCount: 2
architecture: replicaset
# global:
#   storageClass: "nfs-client"
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    # annotations:
    #   lb.kubesphere.io/v1alpha1: openelb
    #   eip.openelb.kubesphere.io/v1alpha2: eip-default-pool
  autoDiscovery:
    enabled: true
serviceAccount:
  create: true
automountServiceAccountToken: true
rbac:
  create: true
